### ISSUE TITLE
Plugin executable missing for arm64 architecture

### ISSUE THREAD

**Issue by gytisrepecka** [RedisTimeSeries/grafana-redis-datasource#48]
### Describe the bug
ARM64 executable missing.

### Version
Redis plugin for Grafana v1.1.2
Grafana  v7.1.3
Ubuntu focal v20.04 (arm64)

### Steps to reproduce

1. Install plugin using `sudo grafana-cli plugins install redis-datasource`;
2. Restart `grafana-server` service;
3. Service status shows error: `lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=redis-datasource error="fork/exec /var/lib/grafana/plugins/redis-datasource/redis-datasource_linux_arm64: no such file or directory"`;
4. When saving datasource error is shown: `Plugin health check failed`.

### Expected behavior
Error should not be shown in service status and plugin should work.

I believe executable for arm64 is expected in `/var/lib/grafana/plugins/redis-datasource`. Currently it contains only following:
```
redis-datasource_darwin_amd64
redis-datasource_linux_amd64
redis-datasource_windows_amd64.exe
```

**Comment by mikhailredis** [comment]
Hello @gytisrepecka, thank you for submitting the issue.

Unfortunately, Linux on Arm64 is not supported in Grafana SDK `grafana-plugin-sdk-go` and I have submitted enhancement request https://github.com/grafana/grafana-plugin-sdk-go/issues/220.

Meanwhile, I create a branch with linux_arm64 binary inside [https://github.com/RedisTimeSeries/grafana-redis-datasource/archive/feat/arm64.zip](https://github.com/RedisTimeSeries/grafana-redis-datasource/archive/feat/arm64.zip).

Do you want to try it and let me know if it works for you? Because the plugin is unsigned, you will need to allow unsigned plugin as described in the [BUILD](https://github.com/RedisTimeSeries/grafana-redis-datasource/blob/master/BUILD.md) instructions.

**Comment by gytisrepecka** [comment]
Thanks for detailed instructions, @mikhailredis - executable from **feat/arm64** works smooth on my [Khadas VIM3 Pro](https://www.khadas.com/vim3)!

**Comment by mikhailredis** [comment]
@gytisrepecka Thank you for the update. I will include support for Linux on arm64 in 1.2.0.
I hope PR will be included in Grafana SDK: https://github.com/grafana/grafana-plugin-sdk-go/pull/221.

**Comment by gytisrepecka** [comment]
Awesome, thanks @mikhailredis !
